#!/bin/sh
#!/bin/bash
echo Welcome to my custom linux image
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

echo "mount -t proc none /proc"
echo "mount -t sysfs none /sys"

exec /sbin/init "$@"